site_name: 纸媒工作室-内训材料整合
site_url: https://grapesea.github.io/paperstudio/
theme: 
  name: material
  logo: graph/logo.jpg
# pages:
# - [index.md, Home]
# - [about.md, About]
  favicon: graph/logo.jpg
  features:
    - search.highlight
#    - navigation.instant
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
nav:
  - 首页: index.md
  - 纳新面试: team/index.md
  - 工作指南: 
    - 前言：版本迭代记录与致谢: instruct/index.md
    - 纸媒工作流程: instruct/1.workflow/index.md
    - 文编工作: instruct/2.text/index.md
    - 美编工作: instruct/3.art/index.md
    - 杂志发放: instruct/4.distribute/index.md
    - 二课分申请: instruct/5.score/index.md
  - 管理条例: 
    - 条例目录: rule/index.md
    - 浙江大学竺可桢学院全媒体中心章程: rule/constitution/index.md
    - 浙江大学竺可桢学院学生评价实施细则: rule/detail/index.md
    - 竺可桢学院公共空间使用办法（试行）: rule/method/index.md
  - 相关资源: 
    - 资源目录: resource/index.md
    - 全媒体资源: resource/media/index.md
    - 字体资源: resource/font/index.md
    - 图片资源: resource/photo/index.md
    - 其它资源: resource/etc/index.md